---
- hosts: localhost
  become: true
  vars_files:
    - network_topology.yml  # Change this to your real YAML file path

  tasks:

  - debug:
      msg: "Let's find the namespaces:"

  - name: Create a namespace named subnet1
    community.general.ip_netns:
      name: "{{item.subnet_id}}"
      state: present
    loop: "{{network.subnets}}"
    when: item.bridge == "no"
  - debug:
      msg: "Let's see if we can make some ovs internal interfaces: "

  - name: Create OVS bridges
    openvswitch.openvswitch.openvswitch_bridge:
      bridge: "{{item.subnet_id}}_sw"
      state: present
    loop: "{{network.subnets}}"
    when: item.bridge == "no"

  # - debug:
  #     msg: "Let's see if we can make some ovs internal interfaces:"

  # - name: Create OVS internal interfaces
  #   openvswitch.openvswitch.openvswitch_port:
  #     bridge: "{{item.subnet_id}}_sw"
  #     port: "{{item.subnet_id}}_sw_p"
  #     state: present
  #   loop: "{{network.subnets}}"
  #   when: item.switch==true

  - name: build switches -- create tmp file
    template:
      src: build_switch.j2
      dest: /tmp/build_switch.sh

  - name: build switch -- execute file
    script: /tmp/build_switch.sh

  - name: build router -- create tmp file
    template:
      src: build_router.j2
      dest: /tmp/build_router.sh

  - name: build router -- execute tmp file
    script: /tmp/build_router.sh

  - name: build hosts -- create tmp file
    template:
      src: build_hosts.j2
      dest: /tmp/build_hosts.sh

  - name: build hosts -- execute file
    script: /tmp/build_hosts.sh

  - name: set up NAT -- create tmp file
    template:
      src: set_up_nat.j2
      dest: /tmp/set_up_nat.sh

  - name: set up NAT -- execute file
    script: /tmp/set_up_nat.sh
