---
- hosts: localhost
  become: true
  vars_files:
    - network_topology.yml  # Change this to your real YAML file path

  tasks:

  - name: Delete namespaces
    community.general.ip_netns:
      name: "{{item.subnet_id}}"
      state: absent
    loop: "{{network.subnets}}"

  - name: Delete OVS bridges and ports
    openvswitch.openvswitch.openvswitch_bridge:
      bridge: "{{item.subnet_id}}_sw"
      state: absent
    loop: "{{network.subnets}}"
  
  - name: Delete routers
    community.general.ip_netns:
      name: "{{ item.subnet_id }}"
      state: absent
    loop: "{{ network.routers }}"

  - name: Delete hosts
    community.general.ip_netns:
      name: "{{ item.name }}"
      state: absent
    loop: "{{ network.hosts }}"

  - name: Delete KVM VM Bridge(s)
    command: sudo ip link del dev br0

  - name: Remove port forwarding for the flask server as a security measure
    command: sudo iptables -P FORWARD DROP && sudo iptables -F FORWARD && sudo iptables -t nat -F
    ignore_errors: yes
