---
- hosts: localhost
  become: true
  vars_files:
    - /home/student/final/network_topology.yml  # Change this to your real YAML file path

  tasks:

  - debug:
      msg: "Let's find the namespaces:"

  - name: Create a namespace named subnet1
    community.general.ip_netns:
      name: "{{item.subnet_id}}"
      state: present
    loop: "{{network.subnets}}"
    when: item.switch==true

  - debug:
      msg: "Let's see if we can make some ovs internal interfaces: "

  - name: Create OVS bridges
    openvswitch.openvswitch.openvswitch_bridge:
      bridge: "{{item.subnet_id}}_sw"
      state: present
    loop: "{{network.subnets}}"
    when: item.switch==true

  - debug:
      msg: "Let's see if we can make some ovs internal interfaces:"

  - name: Create OVS internal interfaces
    openvswitch.openvswitch.openvswitch_port:
      bridge: "{{item.subnet_id}}_sw"
      port: "{{item.subnet_id}}_sw_p"
      state: present
    loop: "{{network.subnets}}"
    when: item.switch==true

  - name: Connect ovs interfaces to namespaces -- create tmp file
    template:
      src: int_to_ns.j2
      dest: /tmp/int_to_ns.sh

  - name: Connect ovs interfaces to namespaces -- execute file
    script: /tmp/int_to_ns.sh
